package com.kairos.app.ui.groceries

/**
 * Every item Kairos ships a custom `kairos:` icon for, with its canonical name —
 * the app-side mirror of the web repo's `src/lib/groceries/suggestions.ts`.
 *
 * The add-an-item list is normally just the household's own catalog, so an item
 * nobody has bought yet isn't offerable and gets typed (and mistyped) by hand.
 * These are shown alongside the catalog, deduped by name, so the whole custom
 * icon set is pickable with the spelling the server's matcher expects.
 *
 * A suggestion is not a catalog row: picking one adds the item by name, and the
 * server creates the catalog entry and guesses the icon — which lands on the icon
 * named here. Bundled rather than fetched so the list works offline; keep it in
 * step with the web file whenever icons are added.
 */
data class GrocerySuggestion(val name: String, val icon: String)

val GROCERY_SUGGESTIONS: List<GrocerySuggestion> = listOf(
    GrocerySuggestion("Air freshener", "kairos:air-freshener"),
    GrocerySuggestion("Allergy medicine", "kairos:allergy-medicine"),
    GrocerySuggestion("Almond milk", "kairos:almond-milk"),
    GrocerySuggestion("Almonds", "kairos:almonds"),
    GrocerySuggestion("Apple cider", "kairos:apple-cider"),
    GrocerySuggestion("Apple juice", "kairos:apple-juice"),
    GrocerySuggestion("Asparagus", "kairos:asparagus"),
    GrocerySuggestion("Avocado oil", "kairos:avocado-oil"),
    GrocerySuggestion("Baby food", "kairos:baby-food"),
    GrocerySuggestion("Baby formula", "kairos:baby-formula"),
    GrocerySuggestion("Baby wipes", "kairos:baby-wipes"),
    GrocerySuggestion("Backpacking food", "kairos:backpacking-food"),
    GrocerySuggestion("Baking powder", "kairos:baking-powder"),
    GrocerySuggestion("Baking soda", "kairos:baking-soda"),
    GrocerySuggestion("Bandages", "kairos:bandages"),
    GrocerySuggestion("Batteries", "kairos:batteries-pack"),
    GrocerySuggestion("BBQ sauce", "kairos:bbq-sauce"),
    GrocerySuggestion("Beef jerky", "kairos:beef-jerky"),
    GrocerySuggestion("Beer", "kairos:beer"),
    GrocerySuggestion("Birthday candles", "kairos:birthday-candles"),
    GrocerySuggestion("Black olives", "kairos:black-olives"),
    GrocerySuggestion("Black pepper", "kairos:black-pepper"),
    GrocerySuggestion("Bleach", "kairos:bleach"),
    GrocerySuggestion("Block cheese", "kairos:block-cheese"),
    GrocerySuggestion("Body wash", "kairos:body-wash"),
    GrocerySuggestion("Bourbon", "kairos:bourbon"),
    GrocerySuggestion("Breadcrumbs", "kairos:breadcrumbs"),
    GrocerySuggestion("Brisket", "kairos:brisket"),
    GrocerySuggestion("Broth", "kairos:broth"),
    GrocerySuggestion("Brown sugar", "kairos:brown-sugar"),
    GrocerySuggestion("Brussels sprouts", "kairos:brussels-sprouts"),
    GrocerySuggestion("Butter sticks", "kairos:butter-sticks"),
    GrocerySuggestion("Canned beans", "kairos:canned-beans"),
    GrocerySuggestion("Canned goods", "kairos:canned-goods"),
    GrocerySuggestion("Canned tomatoes", "kairos:canned-tomatoes"),
    GrocerySuggestion("Canned tuna", "kairos:canned-tuna"),
    GrocerySuggestion("Cannoli", "kairos:cannoli"),
    GrocerySuggestion("Cantaloupe", "kairos:cantaloupe"),
    GrocerySuggestion("Car air filter", "kairos:car-air-filter"),
    GrocerySuggestion("Car oil filter", "kairos:car-oil-filter"),
    GrocerySuggestion("Cashews", "kairos:cashews"),
    GrocerySuggestion("Casserole", "kairos:casserole"),
    GrocerySuggestion("Cat food", "kairos:cat-food"),
    GrocerySuggestion("Cat litter", "kairos:cat-litter"),
    GrocerySuggestion("Catfish", "kairos:catfish"),
    GrocerySuggestion("Cauliflower", "kairos:cauliflower"),
    GrocerySuggestion("Celery", "kairos:celery"),
    GrocerySuggestion("Champagne", "kairos:champagne"),
    GrocerySuggestion("Cheddar", "kairos:cheddar"),
    GrocerySuggestion("Chicken breast", "kairos:chicken-breast"),
    GrocerySuggestion("Chicken thighs", "kairos:chicken-thighs"),
    GrocerySuggestion("Chicken wings", "kairos:chicken-wings"),
    GrocerySuggestion("Chili powder", "kairos:chili-powder"),
    GrocerySuggestion("Chips", "kairos:chips-bag"),
    GrocerySuggestion("Chocolate chips", "kairos:chocolate-chips"),
    GrocerySuggestion("Chocolate milk", "kairos:chocolate-milk"),
    GrocerySuggestion("Cinnamon", "kairos:cinnamon"),
    GrocerySuggestion("Clams", "kairos:clams"),
    GrocerySuggestion("Cleaning spray", "kairos:cleaning-spray"),
    GrocerySuggestion("Cocktail", "kairos:cocktail"),
    GrocerySuggestion("Coconut milk", "kairos:coconut-milk"),
    GrocerySuggestion("Coconut water", "kairos:coconut-water"),
    GrocerySuggestion("Cod", "kairos:cod"),
    GrocerySuggestion("Coffee", "kairos:coffee-bag"),
    GrocerySuggestion("Coffee filters", "kairos:coffee-filters"),
    GrocerySuggestion("Cold cuts", "kairos:cold-cuts"),
    GrocerySuggestion("Conditioner", "kairos:conditioner"),
    GrocerySuggestion("Cooking spray", "kairos:cooking-spray"),
    GrocerySuggestion("Cornmeal", "kairos:corn-meal"),
    GrocerySuggestion("Cornstarch", "kairos:cornstarch"),
    GrocerySuggestion("Cottage cheese", "kairos:cottage-cheese"),
    GrocerySuggestion("Cotton swabs", "kairos:cotton-swabs"),
    GrocerySuggestion("Crab legs", "kairos:crab-legs"),
    GrocerySuggestion("Crackers", "kairos:crackers-box"),
    GrocerySuggestion("Cranberry juice", "kairos:cranberry-juice"),
    GrocerySuggestion("Crawfish", "kairos:crawfish"),
    GrocerySuggestion("Cream cheese", "kairos:cream-cheese"),
    GrocerySuggestion("Creamer", "kairos:creamer"),
    GrocerySuggestion("Cumin", "kairos:cumin"),
    GrocerySuggestion("Deli ham", "kairos:deli-ham"),
    GrocerySuggestion("Deodorant", "kairos:deodorant"),
    GrocerySuggestion("Diapers", "kairos:diapers"),
    GrocerySuggestion("Dinner rolls", "kairos:dinner-rolls"),
    GrocerySuggestion("Dish soap", "kairos:dish-soap"),
    GrocerySuggestion("Dishwasher pods", "kairos:dishwasher-pods"),
    GrocerySuggestion("Distilled water", "kairos:distilled-water"),
    GrocerySuggestion("Dog food", "kairos:dog-food"),
    GrocerySuggestion("Doritos", "kairos:doritos"),
    GrocerySuggestion("Dryer sheets", "kairos:dryer-sheets"),
    GrocerySuggestion("Egg noodles", "kairos:egg-noodles"),
    GrocerySuggestion("Eggs", "kairos:eggs-carton"),
    GrocerySuggestion("Energy drink", "kairos:energy-drink"),
    GrocerySuggestion("English muffins", "kairos:english-muffins"),
    GrocerySuggestion("Fajitas", "kairos:fajitas"),
    GrocerySuggestion("Feminine care", "kairos:feminine-care"),
    GrocerySuggestion("Feta", "kairos:feta"),
    GrocerySuggestion("Filet mignon", "kairos:filet-mignon"),
    GrocerySuggestion("First aid supplies", "kairos:first-aid"),
    GrocerySuggestion("Fish fillets", "kairos:fish-fillet"),
    GrocerySuggestion("Fish sticks", "kairos:fish-sticks"),
    GrocerySuggestion("Floss", "kairos:floss"),
    GrocerySuggestion("Flour", "kairos:flour"),
    GrocerySuggestion("Foil", "kairos:foil"),
    GrocerySuggestion("Frozen dinner", "kairos:frozen-dinner"),
    GrocerySuggestion("Frozen pizza", "kairos:frozen-pizza"),
    GrocerySuggestion("Frozen vegetables", "kairos:frozen-veggies"),
    GrocerySuggestion("Garlic powder", "kairos:garlic-powder"),
    GrocerySuggestion("Gin", "kairos:gin"),
    GrocerySuggestion("Granola", "kairos:granola"),
    GrocerySuggestion("Granola bars", "kairos:granola-bars"),
    GrocerySuggestion("Grape juice", "kairos:grape-juice"),
    GrocerySuggestion("Green beans", "kairos:green-beans"),
    GrocerySuggestion("Green onion", "kairos:green-onion"),
    GrocerySuggestion("Ground beef", "kairos:ground-beef"),
    GrocerySuggestion("Ground sausage", "kairos:ground-sausage"),
    GrocerySuggestion("Ground turkey", "kairos:ground-turkey"),
    GrocerySuggestion("Guacamole", "kairos:guacamole"),
    GrocerySuggestion("Hamburger buns", "kairos:hamburger-buns"),
    GrocerySuggestion("Hand soap", "kairos:hand-soap"),
    GrocerySuggestion("Heavy cream", "kairos:heavy-cream"),
    GrocerySuggestion("Honey", "kairos:honey-jar"),
    GrocerySuggestion("Hot chocolate", "kairos:hot-chocolate"),
    GrocerySuggestion("Hot dog buns", "kairos:hot-dog-buns"),
    GrocerySuggestion("Hummus", "kairos:hummus"),
    GrocerySuggestion("Ice", "kairos:ice"),
    GrocerySuggestion("Iceberg lettuce", "kairos:iceberg-lettuce"),
    GrocerySuggestion("Iced tea", "kairos:iced-tea"),
    GrocerySuggestion("Imitation crab", "kairos:imitation-crab"),
    GrocerySuggestion("Italian bread", "kairos:italian-bread"),
    GrocerySuggestion("Italian seasoning", "kairos:italian-seasoning"),
    GrocerySuggestion("Jam", "kairos:jam"),
    GrocerySuggestion("K-Cups", "kairos:k-cups"),
    GrocerySuggestion("Ketchup", "kairos:ketchup"),
    GrocerySuggestion("Kombucha", "kairos:kombucha"),
    GrocerySuggestion("Lasagna", "kairos:lasagna"),
    GrocerySuggestion("Laundry detergent", "kairos:laundry-detergent"),
    GrocerySuggestion("Lemonade", "kairos:lemonade"),
    GrocerySuggestion("Light bulbs", "kairos:light-bulbs"),
    GrocerySuggestion("Lobster tail", "kairos:lobster-tail"),
    GrocerySuggestion("Lotion", "kairos:lotion"),
    GrocerySuggestion("Mac and cheese", "kairos:mac-and-cheese"),
    GrocerySuggestion("Macaroni", "kairos:macaroni"),
    GrocerySuggestion("Mahi-mahi", "kairos:mahi-mahi"),
    GrocerySuggestion("Mayonnaise", "kairos:mayo"),
    GrocerySuggestion("Meatballs", "kairos:meatballs"),
    GrocerySuggestion("Meatloaf", "kairos:meatloaf"),
    GrocerySuggestion("Medicine", "kairos:medicine"),
    GrocerySuggestion("Milk", "kairos:milk-carton"),
    GrocerySuggestion("Motor oil", "kairos:motor-oil"),
    GrocerySuggestion("Mozzarella", "kairos:mozzarella"),
    GrocerySuggestion("Mussels", "kairos:mussels"),
    GrocerySuggestion("Mustard", "kairos:mustard"),
    GrocerySuggestion("Napkins", "kairos:napkins"),
    GrocerySuggestion("Oatmeal", "kairos:oatmeal-canister"),
    GrocerySuggestion("Olive oil", "kairos:olive-oil"),
    GrocerySuggestion("Olives", "kairos:olives-jar"),
    GrocerySuggestion("Onion powder", "kairos:onion-powder"),
    GrocerySuggestion("Orange juice", "kairos:orange-juice"),
    GrocerySuggestion("Oregano", "kairos:oregano"),
    GrocerySuggestion("Pain reliever", "kairos:pain-reliever"),
    GrocerySuggestion("Pancake mix", "kairos:pancake-mix"),
    GrocerySuggestion("Paper plates", "kairos:paper-plates"),
    GrocerySuggestion("Paper towels", "kairos:paper-towels"),
    GrocerySuggestion("Paprika", "kairos:paprika"),
    GrocerySuggestion("Parmesan", "kairos:parmesan"),
    GrocerySuggestion("Pasta sauce", "kairos:pasta-sauce"),
    GrocerySuggestion("Peanut butter", "kairos:peanut-butter"),
    GrocerySuggestion("Penne", "kairos:penne"),
    GrocerySuggestion("Pepperoni", "kairos:pepperoni"),
    GrocerySuggestion("Pet treats", "kairos:pet-treats"),
    GrocerySuggestion("Pickles", "kairos:pickles-jar"),
    GrocerySuggestion("Pistachios", "kairos:pistachios"),
    GrocerySuggestion("Pita bread", "kairos:pita-bread"),
    GrocerySuggestion("Plastic cutlery", "kairos:plastic-cutlery"),
    GrocerySuggestion("Plastic wrap", "kairos:plastic-wrap"),
    GrocerySuggestion("Plums", "kairos:plums"),
    GrocerySuggestion("Pomegranate", "kairos:pomegranate"),
    GrocerySuggestion("Pork chops", "kairos:pork-chops"),
    GrocerySuggestion("Protein bar", "kairos:protein-bar"),
    GrocerySuggestion("Protein powder", "kairos:protein-powder"),
    GrocerySuggestion("Ravioli", "kairos:ravioli"),
    GrocerySuggestion("Razors", "kairos:razors"),
    GrocerySuggestion("Red onion", "kairos:red-onion"),
    GrocerySuggestion("Red potato", "kairos:red-potato"),
    GrocerySuggestion("Ribeye steak", "kairos:ribeye-steak"),
    GrocerySuggestion("Ribs", "kairos:ribs"),
    GrocerySuggestion("Rice", "kairos:rice-bag"),
    GrocerySuggestion("Romaine lettuce", "kairos:romaine-lettuce"),
    GrocerySuggestion("Rotisserie chicken", "kairos:rotisserie-chicken"),
    GrocerySuggestion("Rum", "kairos:rum"),
    GrocerySuggestion("Russet potato", "kairos:russet-potato"),
    GrocerySuggestion("Salad dressing", "kairos:salad-dressing"),
    GrocerySuggestion("Salami", "kairos:salami"),
    GrocerySuggestion("Salmon", "kairos:salmon"),
    GrocerySuggestion("Salsa", "kairos:salsa"),
    GrocerySuggestion("Scallops", "kairos:scallops"),
    GrocerySuggestion("Shampoo", "kairos:shampoo"),
    GrocerySuggestion("Shredded cheese", "kairos:shredded-cheese"),
    GrocerySuggestion("Shrimp", "kairos:shrimp"),
    GrocerySuggestion("Sirloin steak", "kairos:sirloin-steak"),
    GrocerySuggestion("Sliced cheese", "kairos:sliced-cheese"),
    GrocerySuggestion("Soda", "kairos:soda-bottle"),
    GrocerySuggestion("Soup", "kairos:soup-bowl"),
    GrocerySuggestion("Sour cream", "kairos:sour-cream"),
    GrocerySuggestion("Soy sauce", "kairos:soy-sauce"),
    GrocerySuggestion("Spaghetti", "kairos:spaghetti"),
    GrocerySuggestion("Sparkling water", "kairos:sparkling-water"),
    GrocerySuggestion("Spices", "kairos:spice-jar"),
    GrocerySuggestion("Sponges", "kairos:sponges"),
    GrocerySuggestion("Sports drink", "kairos:sports-drink"),
    GrocerySuggestion("Stir-fry", "kairos:stir-fry"),
    GrocerySuggestion("Storage bags", "kairos:storage-bags"),
    GrocerySuggestion("String cheese", "kairos:string-cheese"),
    GrocerySuggestion("Sugar", "kairos:sugar"),
    GrocerySuggestion("Sunflower seeds", "kairos:sunflower-seeds"),
    GrocerySuggestion("Sunscreen", "kairos:sunscreen"),
    GrocerySuggestion("Supplements", "kairos:supplements"),
    GrocerySuggestion("Sweet tea", "kairos:sweet-tea"),
    GrocerySuggestion("Syrup", "kairos:syrup"),
    GrocerySuggestion("Tacos", "kairos:tacos-plate"),
    GrocerySuggestion("Tequila", "kairos:tequila"),
    GrocerySuggestion("Tilapia", "kairos:tilapia"),
    GrocerySuggestion("Tissues", "kairos:tissues"),
    GrocerySuggestion("Tofu", "kairos:tofu"),
    GrocerySuggestion("Tomato paste", "kairos:tomato-paste"),
    GrocerySuggestion("Toothpaste", "kairos:toothpaste"),
    GrocerySuggestion("Tortilla chips", "kairos:tortilla-chips"),
    GrocerySuggestion("Tortillas", "kairos:tortillas"),
    GrocerySuggestion("Trash bags", "kairos:trash-bags"),
    GrocerySuggestion("Tuna", "kairos:tuna"),
    GrocerySuggestion("Turkey jerky", "kairos:turkey-jerky"),
    GrocerySuggestion("Vegetable oil", "kairos:vegetable-oil"),
    GrocerySuggestion("Vinegar", "kairos:vinegar"),
    GrocerySuggestion("Vitamins", "kairos:vitamins"),
    GrocerySuggestion("Vodka", "kairos:vodka"),
    GrocerySuggestion("Walnuts", "kairos:walnuts"),
    GrocerySuggestion("Whipped cream can", "kairos:whipped-cream-can"),
    GrocerySuggestion("Whipped cream tub", "kairos:whipped-cream-tub"),
    GrocerySuggestion("Whiskey", "kairos:whiskey"),
    GrocerySuggestion("Wine", "kairos:wine"),
    GrocerySuggestion("Yellow onion", "kairos:yellow-onion"),
    GrocerySuggestion("Yogurt", "kairos:yogurt"),
    GrocerySuggestion("Ziti", "kairos:ziti"),
    GrocerySuggestion("Zucchini", "kairos:zucchini"),
)
